# Secrets from 1Password, on demand — nothing is cached on disk.
#
# Only `op://` *references* are managed here (they are not secrets, so they can
# live in the public repo). The values are resolved by the 1Password CLI at the
# moment they are needed, authenticated through the desktop app (Touch ID /
# system auth) or `op signin` on headless hosts:
#
#   with-secrets claude          # run one command with the variables injected
#   secrets-load                 # export them into the current zsh session
#   secrets-unload               # drop them again
#
# Extra, machine-local references go in ~/.config/op/secrets.local.env
# (untracked, same KEY=op://vault/item/field format).
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.dotfiles.secrets;
  envFile = "${config.xdg.configHome}/op/secrets.env";
  localEnvFile = "${config.xdg.configHome}/op/secrets.local.env";

  # Shell snippet that lists the env files to use (managed + optional local).
  envFilesSh = ''
    files=("${envFile}")
    [[ -f "${localEnvFile}" ]] && files+=("${localEnvFile}")
  '';

  withSecrets = pkgs.writeShellApplication {
    name = "with-secrets";
    runtimeInputs = [ pkgs._1password-cli ];
    text = ''
      if [[ $# -eq 0 || $1 == -h || $1 == --help ]]; then
        echo "Usage: with-secrets <command> [args...]" >&2
        echo "Runs <command> with the variables from ${envFile}" >&2
        echo "(and ${localEnvFile} if present) resolved from 1Password." >&2
        exit 2
      fi
      ${envFilesSh}
      args=()
      for f in "''${files[@]}"; do args+=("--env-file=$f"); done
      # --no-masking: masking pipes stdout through op, which breaks TUIs
      # (claude, codex, opencode) and adds latency to everything else.
      exec op run "''${args[@]}" --no-masking -- "$@"
    '';
  };
in
{
  options.dotfiles.secrets.env = lib.mkOption {
    type = lib.types.attrsOf lib.types.str;
    default = { };
    example = {
      BRAVE_API_KEY = "op://Personal/BraveAPI/credential";
    };
    description = ''
      Environment variables to resolve from 1Password on demand, as
      `NAME = "op://vault/item/field"`. Rendered to ~/.config/op/secrets.env
      and consumed by `with-secrets` / `secrets-load`.
    '';
  };

  config = lib.mkIf (cfg.env != { }) {
    home.packages = [ withSecrets ];

    xdg.configFile."op/secrets.env".text = ''
      # Generated by home-manager (home/common/cli/onepassword.nix).
      # References only — resolved by `op run` / `op inject` at use time.
    ''
    + lib.concatStringsSep "\n" (lib.mapAttrsToList (k: v: "${k}=${v}") cfg.env)
    + "\n";

    programs.zsh.initContent = ''
      # Resolve ~/.config/op/secrets*.env through 1Password and export the
      # result into this shell. One auth prompt per call; values live only in
      # this process' environment.
      secrets-load() {
        local -a files
        ${envFilesSh}
        # Desktop hosts authenticate through the 1Password app. Headless hosts
        # need a session (`eval $(op signin)`) or a service-account token.
        if [[ -z "''${OP_SERVICE_ACCOUNT_TOKEN:-}" ]] && ! op whoami >/dev/null 2>&1; then
          print -u2 "secrets-load: not signed in to 1Password."
          print -u2 "  interactive: eval \$(op signin)        (after a one-time: op account add)"
          print -u2 "  unattended:  export OP_SERVICE_ACCOUNT_TOKEN=…   (put it in ~/.config/zsh/local.zsh)"
          return 1
        fi
        local f out line
        for f in "''${files[@]}"; do
          # Resolve first, export after: a failed/cancelled auth must not
          # leave a half-exported set behind.
          out="$(op inject -i "$f")" || { print -u2 "secrets-load: op inject failed for $f"; return 1; }
          for line in "''${(f)out}"; do
            [[ -z "$line" || "$line" == \#* ]] && continue
            export "''${line%%=*}=''${line#*=}"
          done
        done
      }
      secrets-unload() {
        local -a files
        ${envFilesSh}
        local f line
        for f in "''${files[@]}"; do
          while IFS= read -r line; do
            [[ -z "$line" || "$line" == \#* ]] && continue
            unset "''${line%%=*}"
          done < "$f"
        done
      }
    '';
  };
}
