[general]
working_directory = "C:/Users/hoop6"

[colors.bright]
black = "0x2E3440"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xD08770"

[colors.cursor]
cursor = "0xECEFF4"
text = "0xECEFF4"

[colors.footer_bar]
background = "0xECEFF4"
foreground = "0xECEFF4"

[colors.hints.end]
background = "0x434C5E"
foreground = "0xECEFF4"

[colors.hints.start]
background = "0x434C5E"
foreground = "0xECEFF4"

[colors.normal]
black = "0x2E3440"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.primary]
background = "0x4C566A"
bright_foreground = "0xECEFF4"
dim_foreground = "0xE5E9F0"
foreground = "0xECEFF4"

[colors.search.focused_match]
background = "0x434C5E"
foreground = "0xECEFF4"

[colors.search.matches]
background = "0x434C5E"
foreground = "0xECEFF4"

[cursor]
style = "Beam"

[font]
size = 14
[font.bold]
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"

[terminal.shell]
program = "C:/Users/hoop6/AppData/Local/Programs/nu/bin/nu.exe"

[window]
opacity = 0.9

[window.padding]
x = 2
y = 2
