-- Generated from the Nix config by: nix run .#export-dotfiles — do not edit by hand.
-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/

local wezterm = require 'wezterm'
local config = wezterm.config_builder and wezterm.config_builder() or {}

local hm_config = {
  ["color_scheme"] = "stylix",
  ["colors"] = {
    ["tab_bar"] = {
      ["active_tab"] = {
        ["bg_color"] = "1e2433",
        ["fg_color"] = "c5d4e8"
      },
      ["background"] = "272d3f",
      ["inactive_tab"] = {
        ["bg_color"] = "4a5368",
        ["fg_color"] = "c5d4e8"
      },
      ["inactive_tab_edge"] = "272d3f",
      ["inactive_tab_hover"] = {
        ["bg_color"] = "c5d4e8",
        ["fg_color"] = "1e2433"
      },
      ["new_tab"] = {
        ["bg_color"] = "4a5368",
        ["fg_color"] = "c5d4e8"
      },
      ["new_tab_hover"] = {
        ["bg_color"] = "c5d4e8",
        ["fg_color"] = "1e2433"
      }
    }
  },
  ["command_palette_bg_color"] = "272d3f",
  ["command_palette_fg_color"] = "c5d4e8",
  ["command_palette_font_size"] = 12,
  ["font"] = (wezterm.font_with_fallback { "HackGen Console NF", "Noto Color Emoji" }),
  ["font_size"] = 14,
  ["window_background_opacity"] = 0.9,
  ["window_frame"] = {
    ["active_titlebar_bg"] = "4a5368",
    ["active_titlebar_border_bottom"] = "4a5368",
    ["active_titlebar_fg"] = "c5d4e8",
    ["border_bottom_color"] = "272d3f",
    ["border_left_color"] = "272d3f",
    ["border_right_color"] = "272d3f",
    ["border_top_color"] = "272d3f",
    ["button_bg"] = "272d3f",
    ["button_fg"] = "c5d4e8",
    ["button_hover_bg"] = "c5d4e8",
    ["button_hover_fg"] = "4a5368",
    ["inactive_titlebar_bg"] = "272d3f",
    ["inactive_titlebar_border_bottom"] = "4a5368",
    ["inactive_titlebar_fg"] = "c5d4e8"
  }
}
for k, v in pairs(hm_config) do
  config[k] = v
end

local _hm_extra = (function()
  local wezterm = require("wezterm")

local is_linux = wezterm.target_triple:find("linux") ~= nil

-- Colors, font (HackGen), font size and opacity all come from Stylix —
-- do not set them here, or they would silently override the theme.
return {
  window_padding = {
    left = 10,
    right = 10,
    top = 10,
    bottom = 10,
  },

  use_fancy_tab_bar = false,
  hide_tab_bar_if_only_one_tab = true,
  window_decorations = is_linux and "RESIZE" or "TITLE | RESIZE",

  front_end = "WebGpu",
  enable_wayland = is_linux,
  use_ime = true,
  check_for_updates = false,

  -- Clipboard relies on WezTerm defaults (no override needed):
  --   * SHIFT bypasses an app's mouse capture (e.g. zellij), so
  --     SHIFT+drag selects and copies to the system clipboard — and
  --     SHIFT+wheel scrolls WezTerm natively.
  --   * OSC 52 writes from remote programs (over SSH) are honored,
  --     which is how a remote zellij's copy reaches the Mac clipboard.
  scrollback_lines = 10000,
}

end)()
if type(_hm_extra) == "table" then
  for k, v in pairs(_hm_extra) do
    config[k] = v
  end
end

return config
